### ISSUE TITLE
Dutch National Flag Sorting Algorithm in java

### ISSUE THREAD

**Issue by mondalraj** [meetpatel2220/hacktoberfest2021#28]
I am making a pull request for this issue
Please assign me this issue under the tag of hacktoberfest.

**Comment by mondalraj** [comment]
Done 
refer pull request #30

**Comment by rushikeshadhav** [comment]
Can I contribute? I know Dutch National Flag Sorting Algorithm
Please assign this to me.
Thank you

**Comment by meetpatel2220** [comment]
> Can I contribute? I know Dutch National Flag Sorting Algorithm Please assign this to me. Thank you

Yes bro you can send PR
