### ISSUE TITLE
Make some folders based on language or projects

### ISSUE THREAD

**Issue by Shubham20015** [meetpatel2220/hacktoberfest2021#34]
You can make folders like :
1. CPP
2. JAVA
3. Web Dev Projects
4. AI/ML Projects
5. DSA
6. Competitive Programming
It's only my suggestion then it easy for beginners to make PR 😄

**Comment by meetpatel2220** [comment]
done bro

**Comment by iamanshulgit** [comment]
Hello, Is it still open, if it is can I contribute to this? Thank you

**Comment by meetpatel2220** [comment]
> Hello, I have added a file and sent a PR. Please check the same. Thank you

done
