### ISSUE TITLE
any sorting algorithem in cpp

### ISSUE THREAD

**Issue by meetpatel2220** [meetpatel2220/hacktoberfest2021#36]

**Comment by jazxii** [comment]
Can i take this up?

**Comment by vidhik2002** [comment]
heyy @meetpatel2220 , could i pls work on this?

**Comment by akarshan2602** [comment]
Hey @meetpatel2220 can i please work on this issue? I am already familiar with all the sorting algorithms u have mentioned.

**Comment by karanS08** [comment]
Hey @meetpatel2220 , 
I am interested in  contributing . please assign me with this as I know implementations of many sorting methods in c or c++.
I am really looking forward for this .

**Comment by meetpatel2220** [comment]
yes @karanS08  @jazxii  @akarshan2602  @vidhik2002  you can send pull request

**Comment by viralkumar28** [comment]
@meetpatel2220  hey can  you assign me I can  do in java
