### ISSUE TITLE
any searching algorithem in java

### ISSUE THREAD

**Issue by meetpatel2220** [meetpatel2220/hacktoberfest2021#37]
add your file in java folder
otherwise i will not merge it

**Comment by RiyaBhandari-2811** [comment]
Hey , can i work on these ???

**Comment by jazxii** [comment]
Can i take up this?

**Comment by jazxii** [comment]
hey @meetpatel2220 pls check my PR #40

**Comment by Gaurika-Gupta** [comment]
Hello, Can I work on this Issue? I wish to add the code of Exponential Search.

**Comment by shivani0126** [comment]
Hello
I want to contribute to this ,can I add Jump Search and Fibonacci Search.

**Comment by meetpatel2220** [comment]
yes you can work on this @RiyaBhandari-2811  @Gaurika-Gupta  @shivani0126
