### ISSUE TITLE
List of git commands with example

### ISSUE THREAD

**Issue by meetpatel2220** [meetpatel2220/hacktoberfest2021#54]

**Comment by rushikeshadhav** [comment]
I will do it. Please assign me

**Comment by akarshan2602** [comment]
hey, can i work on it??

**Comment by rushikeshadhav** [comment]
@meetpatel2220 hey can you please assign me. I can do this.

**Comment by rushikeshadhav** [comment]
How can I assign you. This is your repository, you raised this issue.
Can you assign me ? I can do this

**Comment by meetpatel2220** [comment]
@rushikeshadhav  you can create new good issue ,if you want
i will add label

**Comment by akarshan2602** [comment]
Wait why is it showing closed?
