### ISSUE TITLE
List of 5 good issues for begineers

### ISSUE THREAD

**Issue by meetpatel2220** [meetpatel2220/hacktoberfest2021#81]
add list of your issues in comment box

**Comment by m1ga** [comment]
* Search for proper repos to contribute to: join the discord https://discord.com/invite/hacktoberfest and check the `project-sharing` section
* don't contribute to DSA (Data Structure and Algorithm) repos as they are considered as spam and will likely be removed (like this repo :wink:)
* use https://github.com/search?o=desc&q=label%3Ahacktoberfest&s=created&state=open&type=Issues and check the repo if it has been there for longer than October and if there is a valid purpos for it being there (and not just a `create random PR` repo)
* wait for you to be assigned to an issue before working on it and check if there is not a PR already
* if a repo is called `accept-all`, `hacktoberfest2021` or so it's likely it's a repo just for contributions/shirts -> spam
* be nice :heart: 

That said: you can always contribute to any repo and help out - even in the other months. It's not just October for free swag!
